site_name: pm_toolbox
nav:
  - Home: index.md
  - Reference: reference.md
  - Tutorials: tutorials.md
theme: readthedocs
docs_dir: 'docs'
site_dir: 'site'
copyright: Copyright &copy; 2021 - 2021, Sergey Primakov & Lisa Lavrova.